name: StructureBlockLibSample
version: 1.10.0
author: Shynixn
main: com.github.shynixn.structureblocklibsample.StructureBlockLibSamplePlugin
commands:
  structure:
    description: Manages structures.
    useage: /<command>
    permission: structureblocklibsample.admin
    permission-message: You don't have permission.
  structureblock:
    description: Manages structure blocks.
    usage: /<command>
    permission: structureblocklibsample.admin
    permission-message: You don't have permission.